# Generated by Django 5.1.5 on 2025-01-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Stars',
            field=models.IntegerField(null=True),
        ),
    ]
