# Generated by Django 5.1.5 on 2025-02-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Stars',
            new_name='stars',
        ),
    ]
