# Generated by Django 5.1.5 on 2025-02-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_stars_customuser_stars"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="coins",
            field=models.IntegerField(null=True),
        ),
    ]
