# Generated by Django 5.1.5 on 2025-02-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_customuser_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="games_played",
            field=models.IntegerField(default=0),
        ),
    ]
