# Generated by Django 5.1.5 on 2025-03-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_coins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="average_stars_per_game",
            field=models.FloatField(default=0),
        ),
    ]
