# Generated by Django 5.1.5 on 2025-03-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_customuser_average_stars_per_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="stars",
            field=models.IntegerField(default=0),
        ),
    ]
