# Generated by Django 5.1.5 on 2025-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_customuser_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="average_stars_per_game",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
